# Filtro das cidades

In [1]:
import pandas as pd

In [9]:
df = pd.read_csv ('CelularesSubtraidos_2024.csv', sep = ';')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df.head(3)

C:\Users\Amazonas\AppData\Local\Temp\ipykernel_20184\3512787334.py:1: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv ('CelularesSubtraidos_2024.csv', sep = ';')

,ID_DELEGACIA,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,ANO_BO,NUM_BO,VERSAO,NOME_DEPARTAMENTO_CIRC,NOME_SECCIONAL_CIRC,NOME_DELEGACIA_CIRC,NOME_MUNICIPIO_CIRC,DATA_OCORRENCIA_BO,HORA_OCORRENCIA,DESCRICAO_APRESENTACAO,DATAHORA_REGISTRO_BO,DATA_COMUNICACAO_BO,DATAHORA_IMPRESSAO_BO,DESCR_PERIODO,AUTORIA_BO,FLAG_INTOLERANCIA,TIPO_INTOLERANCIA,FLAG_FLAGRANTE,FLAG_STATUS,DESC_LEI,FLAG_ATO_INFRACIONAL,RUBRICA,DESCR_CONDUTA,DESDOBRAMENTO,CIRCUNSTANCIA,DESCR_TIPOLOCAL,DESCR_SUBTIPOLOCAL,CIDADE,BAIRRO,CEP,LOGRADOURO_VERSAO,LOGRADOURO,NUMERO_LOGRADOURO,LATITUDE,LONGITUDE,CONT_OBJETO,DESCR_MODO_OBJETO,DESCR_TIPO_OBJETO,DESCR_SUBTIPO_OBJETO,DESCR_UNIDADE,QUANTIDADE_OBJETO,MARCA_OBJETO,FLAG_BLOQUEIO,FLAG_DESBLOQUEIO,MES,ANO,CMD,BTL,CIA,CD_IBGE
0,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AG3021,2,DECAP,DECAP - SEDE,DEL.POL.METROPOLITANO,S.PAULO,05/01/2024,NaN,Pela Parte Interessada,06/01/2024,06/01/2024,29/01/2024,A noite,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Outros,NaN,NaN,Terminal/Estação,Metroviário e Ferroviário Metropolitano,S.PAULO,VILA CAMPANELA,8220380.0,2,AVENIDA DO CONTORNO,0.0,NaN,NaN,1005689039,Subtraído,Telecomunicação,Telefone Celular,NaN,1,Samsung,S,N,1,2024,CPC,(vazio),(vazio),3550308
1,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AG3573,2,DECAP,DECAP - SEDE,DEL.POL.METROPOLITANO,S.PAULO,03/01/2024,NaN,Pela Parte Interessada,06/01/2024,05/01/2024,29/01/2024,A noite,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Outros,NaN,NaN,Terminal/Estação,Metroviário e Ferroviário Metropolitano,S.PAULO,VILA CAMPANELA,8220380.0,2,AVENIDA DO CONTORNO,0.0,NaN,NaN,1005689372,Subtraído,Telecomunicação,Telefone Celular,NaN,1,Samsung,S,N,1,2024,CPC,(vazio),(vazio),3550308
2,10112,DECAP,DEL.SEC.1º CENTRO,12º D.P. PARI,S.PAULO,2024,AI6188,2,DECAP,DECAP - SEDE,DEL.POL.METROPOLITANO,S.PAULO,30/12/2023,17:00:00,Pela Parte Interessada,08/01/2024,08/01/2024,10/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Transeunte,NaN,NaN,Terminal/Estação,Metroviário e Ferroviário Metropolitano,S.PAULO,BELEM,0.0,2,ESTAÇÃO METRO BELEM,1.0,"-23,5431932129999","-46,590699946",1005705507,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Samsung,S,N,1,2024,CPC,(vazio),(vazio),3550308

In [11]:
print("Total:", len(df))
print("\nRUBRICA:")
print(df['RUBRICA'].value_counts())

Total: 412527

RUBRICA:
RUBRICA
Roubo (art. 157)                                                                                                  169162
Furto (art. 155)                                                                                                  166728
Perda/Extravio                                                                                                     44147
Localização/Apreensão e Entrega de veículo                                                                         10144
Outros não criminal                                                                                                 2005
Estelionato (art. 171)                                                                                              1996
Localização/Apreensão de veículo                                                                                    1808
Entrega de veículo localizado/apreendido                                                                            1802
Lesão corporal (art. 129)                                                                                           1415
Extorsão (art. 158)                                                                                                 1372
Localização/Apreensão de objeto                                                                                     1358
Localização/Apreensão e Entrega de objeto                                                                           1347
Apropriação indébita (art. 168)                                                                                     1008
Ameaça (art. 147)                                                                                                    955
Violência Doméstica                                                                                                  882
Receptação (art. 180)                                                                                                836
Adulteração de sinal identificador de veículo automotor (art. 311)                                                   450
Apropriação de coisa havida por erro, caso fortuito, força da natureza (art 169)                                     445
Dano (art. 163)                                                                                                      412
Injúria (art. 140)                                                                                                   327
Captura de procurado                                                                                                 268
Associação Criminosa (art. 288)                                                                                      220
Entrega de objeto localizado/apreendido                                                                              218
Caput Corromper ou facilitar a corrupção de menor de 18 anos (244B)                                                  193
Descumprimento de medida protetiva de urgência (art. 24-A)                                                           164
Vias de fato (art. 21)                                                                                               161
Lesão corporal culposa na direção de veículo automotor (Art. 303)                                                    154
Invasão de dispositivo informático                                                                                   152
Extorsão mediante seqüestro (art. 159)                                                                               136
Encontro de Pessoa                                                                                                   125
Colisão                                                                                                              116
Resistência (art. 329)                                                                                               101
Comunicação falsa de crime ou contravenção (art. 340)                                                                 97
Cumprimento de mandado de busca e apreensão                                                                           91
Homicídio (art. 121)                                                                                                  87
Estupro - Art. 213                                                                                                    87
Disparo de arma de fogo (Art. 15)                                                                                     84
Exercício arbitrário das próprias razões (art. 345)                                                                   80
Violação de domicílio (art. 150)                                                                                      80
Seqüestro e cárcere privado (art. 148)                                                                                74
Furto de coisa comum (art. 156)                                                                                       68
Perseguir (art. 147-A)                                                                                                65
Drogas para consumo pessoal sem autorização ou em desacordo (Art.28,caput)                                            65
tráfico drogas (Art.33, caput)                                                                                        63
Desobediência (art. 330)                                                                                              61
Desaparecimento de pessoa                                                                                             55
Posse ou porte ilegal de arma de fogo de uso restrito (Art. 16)                                                       49
Falsa identidade (art. 307)                                                                                           47
Difamação (art. 139)                                                                                                  39
Art 2º - Promover, constituir, financiar ou integrar organização criminosa                                            37
Art. 215A - Importunação Sexual                                                                                       37
Disparo de arma de fogo (art. 28)                                                                                     36
Cumprimento de mandado de prisão temporária                                                                           35
Apreensão de Adolescente                                                                                              33
Fuga de local de acidente (Art. 305)                                                                                  33
Estupro de vulneravel (art.217-A)                                                                                     32
Calúnia (art. 138)                                                                                                    32
Dirigir sem Permissão ou Habilitação (Art. 309)                                                                       29
Morte suspeita                                                                                                        28
Porte ilegal de arma de fogo de uso permitido (Art. 14)                                                               24
Desacato (art. 331)                                                                                                   23
Divulgação de cena de estupro e imagens de nudez, sexo ou pornografia(Art.218-C)                                      19
Violência psicológica contra a mulher (Art. 147-B)                                                                    19
Choque                                                                                                                18
Tortura (Art. 1º)                                                                                                     14
ilícito extrapenal (tema 506 STF)                                                                                     14
Atropelamento                                                                                                         13
Associação para o tráfico (Art.35,caput)                                                                              12
Embriaguez ao volante (Art. 306)                                                                                      12
Incêndio (art. 250, caput)                                                                                            12
Falsidade ideológica (art. 299)                                                                                       11
Homicídio culposo na direção de veículo automotor (Art. 302)                                                          11
Corrupção de menores (art.218)                                                                                         9
Queda acidental                                                                                                        9
Injuriar alguém, ofendendo-lhe a dignidade ou o decoro, em razão de raça, cor, etnia ou procedência nacional.          9
Corrupção ativa (art. 333)                                                                                             8
Comunicação de óbito                                                                                                   8
Constrangimento ilegal (art. 146)                                                                                      8
Posse irregular de arma de fogo de uso permitido (Art.12)                                                              7
Apropriar-se de bens do idoso (Art. 102)                                                                               6
Moeda falsa (art. 289)                                                                                                 6
Favorecimento real (art. 349)                                                                                          6
Omissão de socorro (Art. 135)                                                                                          5
Maus-tratos (art. 136)                                                                                                 5
Praticar ato de abuso a animais (Art. 32)                                                                              5
Usura pecuniária ou real (Art. 4º)                                                                                     4
Supressão de documento (art. 305)                                                                                      4
Praticar a discriminação (Art. 20)                                                                                     4
Deixar de prestar assitência ao idoso (Art. 97)                                                                        4
Capotamento                                                                                                            4
Auto lesão                                                                                                             3
Coação no curso do processo (art. 344)                                                                                 3
Submeter criança ou adolescente a vexame (Art. 232)                                                                    3
Receptação de animal                                                                                                   3
Denunciação caluniosa (art. 339)                                                                                       3
Causas de aumento                                                                                                      3
Morte natural                                                                                                          3
Omissão de socorro (Art. 304)                                                                                          3
Fuga consumada                                                                                                         3
Porte de arma (art. 19)                                                                                                2
Descumprir decisão judicial que defere medida protetiva de urgência prevista nesta Lei:                                2
Favorecimento pessoal (art. 348)                                                                                       2
Produzir substância tóxica (Art. 56)                                                                                   2
Crime contra a ordem tributária (Art. 1º)                                                                              2
Alteração de limites (art. 161)                                                                                        2
Tombamento                                                                                                             2
Posse não justificada de instr. de empr. no furto (art. 25)                                                            2
Favorecimento da prostituição ou outra forma de exploração sexual de vulnerável                                        2
Jogo de azar (art. 50)                                                                                                 2
Direção perigosa de veículo na via pública (art. 34)                                                                   2
Perturbação do trabalho ou do sossego alheios (art. 42)                                                                2
Crime contra as relações de consumo (Art. 7º)                                                                          2
Constranger o preso ou o detento, mediante violência, grave ameaça                                                     2
Art. 308-Participar, na direção de veículo automotor, em via pública, de corrida                                       1
Omissão cautela na guarda/condução animais (art. 31)                                                                   1
Expor a perigo a integridade e saúde (Art. 99)                                                                         1
Prevaricação (art. 319)                                                                                                1
Calúnia (Art. 20)                                                                                                      1
Falsificação de documento particular ou falsificação de cartão                                                         1
Trafegar em velocidade incompatível (Art. 311)                                                                         1
Peculato (art. 312)                                                                                                    1
Perigo de contágio venéreo (art. 130)                                                                                  1
Violação de correspondência (art. 151)                                                                                 1
Entregar produtos cujos componentes possam causar dependência (Art. 243)                                               1
Permitir direção de veículo automotor a pessoa não habilitada (Art. 310)                                               1
Empregar componentes usados (Art. 70)                                                                                  1
Usurpação de função pública (art. 328)                                                                                 1
Evasão/Fuga de Criança ou Adolescente Consumada                                                                        1
Uso de documento falso (Art. 353)                                                                                      1
Falta de habilitação para dirigir veículo (art. 32)                                                                    1
Subtração de incapazes (art. 249)                                                                                      1
Suicídio consumado                                                                                                     1
Utilizar-se de criança ou adolescente em cena de sexo explícito (Art. 240)                                             1
Evasão/Fuga de Paciente de Estabelecimento Hospitalar Consumada                                                        1
Vender ou expor à venda fotografia, vídeo ou outro registro(Art. 241)                                                  1
Inovar, artificiosamente, em caso de acidente automobilístico (Art. 312)                                               1
Falsificação de documento público (art. 297)                                                                           1
Embriaguez (art. 62)                                                                                                   1
Coagir o idoso (Art. 107)                                                                                              1
Abandono de incapaz (art. 133)                                                                                         1
Invadir ou adentrar, clandestina ou astuciosamente, ou à revelia da vontade do ocupante, imóvel alheio ou suas         1
Name: count, dtype: int64

In [14]:
df['NOME_MUNICIPIO'].value_counts().head(20)

NOME_MUNICIPIO
S.PAULO                223785
GUARULHOS               12328
CAMPINAS                 9991
S.ANDRE                  9584
S.BERNARDO DO CAMPO      8200
OSASCO                   7184
PRAIA GRANDE             5309
RIBEIRAO PRETO           4041
DIADEMA                  3970
SOROCABA                 3869
S.VICENTE                3748
ITAQUAQUECETUBA          3635
CARAPICUIBA              3503
MAUA                     3356
SANTOS                   3179
GUARUJA                  3171
S.JOSE DOS CAMPOS        2959
SUZANO                   2882
S.JOSE DO RIO PRETO      2712
TABOAO DA SERRA          2666
Name: count, dtype: int64

In [18]:
df['CIDADE'].value_counts().head(20)

CIDADE
S.PAULO                223785
GUARULHOS               12328
CAMPINAS                 9991
S.ANDRE                  9584
S.BERNARDO DO CAMPO      8200
OSASCO                   7184
PRAIA GRANDE             5309
RIBEIRAO PRETO           4041
DIADEMA                  3970
SOROCABA                 3869
S.VICENTE                3748
ITAQUAQUECETUBA          3635
CARAPICUIBA              3503
MAUA                     3356
SANTOS                   3179
GUARUJA                  3171
S.JOSE DOS CAMPOS        2959
SUZANO                   2882
S.JOSE DO RIO PRETO      2712
TABOAO DA SERRA          2666
Name: count, dtype: int64

In [22]:
df.loc[
    df['NOME_MUNICIPIO'] != df['CIDADE'],
    ['NOME_MUNICIPIO', 'CIDADE']
].value_counts()

Series([], Name: count, dtype: int64)

In [24]:
filtro_sp = df['NOME_MUNICIPIO'].eq('S.PAULO')

df_sp = df.loc[filtro_sp].copy()

In [26]:
df_sp.shape

(223785, 55)

In [28]:
df_sp[['LATITUDE', 'LONGITUDE']].isna().sum()

LATITUDE     31846
LONGITUDE    31846
dtype: int64

In [30]:
df_sp_geo = df_sp.loc[
    df_sp['LATITUDE'].notna() &
    df_sp['LONGITUDE'].notna()
].copy()

df_sp_geo.shape

(191939, 55)

In [32]:
(df_sp_geo['LATITUDE'] == 0).sum()

(df_sp_geo['LONGITUDE'] == 0).sum()

0

In [36]:
df_sp['LATITUDE'] = pd.to_numeric(
    df_sp['LATITUDE'].astype(str).str.replace(',', '.', regex=False),
    errors='coerce'
)

df_sp['LONGITUDE'] = pd.to_numeric(
    df_sp['LONGITUDE'].astype(str).str.replace(',', '.', regex=False),
    errors='coerce'
)

In [38]:
df_sp[['LATITUDE', 'LONGITUDE']].dtypes

LATITUDE     float64
LONGITUDE    float64
dtype: object

In [40]:
df_sp_geo = df_sp.loc[
    df_sp['LATITUDE'].between(-24, -23) &
    df_sp['LONGITUDE'].between(-47, -46)
].copy()

df_sp_geo.shape

(185842, 55)

In [42]:
df_sp_geo.duplicated(
    subset=['NOME_DELEGACIA', 'ANO_BO', 'NUM_BO']
).sum()

35872

In [44]:
df_sp_geo[
    df_sp_geo.duplicated(
        subset=['NOME_DELEGACIA', 'ANO_BO', 'NUM_BO'],
        keep=False
    )
].head(20)

,ID_DELEGACIA,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,ANO_BO,NUM_BO,VERSAO,NOME_DEPARTAMENTO_CIRC,NOME_SECCIONAL_CIRC,NOME_DELEGACIA_CIRC,NOME_MUNICIPIO_CIRC,DATA_OCORRENCIA_BO,HORA_OCORRENCIA,DESCRICAO_APRESENTACAO,DATAHORA_REGISTRO_BO,DATA_COMUNICACAO_BO,DATAHORA_IMPRESSAO_BO,DESCR_PERIODO,AUTORIA_BO,FLAG_INTOLERANCIA,TIPO_INTOLERANCIA,FLAG_FLAGRANTE,FLAG_STATUS,DESC_LEI,FLAG_ATO_INFRACIONAL,RUBRICA,DESCR_CONDUTA,DESDOBRAMENTO,CIRCUNSTANCIA,DESCR_TIPOLOCAL,DESCR_SUBTIPOLOCAL,CIDADE,BAIRRO,CEP,LOGRADOURO_VERSAO,LOGRADOURO,NUMERO_LOGRADOURO,LATITUDE,LONGITUDE,CONT_OBJETO,DESCR_MODO_OBJETO,DESCR_TIPO_OBJETO,DESCR_SUBTIPO_OBJETO,DESCR_UNIDADE,QUANTIDADE_OBJETO,MARCA_OBJETO,FLAG_BLOQUEIO,FLAG_DESBLOQUEIO,MES,ANO,CMD,BTL,CIA,CD_IBGE
12,30125,DEMACRO,DEL.SEC.SANTO ANDRÉ,02º D.P. MAUA,S.PAULO,2024,BK0957,2,DECAP,DECAP - SEDE,DEL.POL.METROPOLITANO,S.PAULO,29/01/2024,09:30:00,Pela Parte Interessada,30/01/2024,30/01/2024,31/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Outros,NaN,§ 4º-B - se o furto mediante fraude é cometido...,Via Pública,Via Pública,S.PAULO,PINHEIROS,5422011.0,2,RUA DOS PINHEIROS,623.0,-23.566325,-46.684428,1005885063,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Apple,N,N,1,2024,CPC,(vazio),(vazio),3550308
13,30125,DEMACRO,DEL.SEC.SANTO ANDRÉ,02º D.P. MAUA,S.PAULO,2024,BK0957,2,DECAP,DECAP - SEDE,DEL.POL.METROPOLITANO,S.PAULO,29/01/2024,09:30:00,Pela Parte Interessada,30/01/2024,30/01/2024,31/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Outros,NaN,§ 4º-B - se o furto mediante fraude é cometido...,Via Pública,Via Pública,S.PAULO,PINHEIROS,5422011.0,2,RUA DOS PINHEIROS,623.0,-23.566325,-46.684428,1005885063,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Apple,S,N,1,2024,CPC,(vazio),(vazio),3550308
25,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AA0983,2,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,30/12/2023,NaN,Pela Parte Interessada,01/01/2024,31/12/2023,15/01/2025,Pela manhã,D,N,NaN,N,CONSUMADO,Não Criminal,N,Localização/Apreensão de objeto,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,SE,1001001.0,1,PRAÇA DA SE,2.0,-23.550556,-46.634343,1005642985,Subtraído,Telecomunicação,Telefone Celular,NaN,1,Apple,S,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
26,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AA0983,2,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,30/12/2023,NaN,Pela Parte Interessada,01/01/2024,31/12/2023,15/01/2025,Pela manhã,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Outros,NaN,NaN,Via Pública,Via Pública,S.PAULO,SE,1001001.0,1,PRAÇA DA SE,2.0,-23.550556,-46.634343,1005642985,Subtraído,Telecomunicação,Telefone Celular,NaN,1,Apple,S,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
42,10101,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,2024,AB5526,2,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,02/01/2024,15:30:00,Pela Parte Interessada,02/01/2024,02/01/2024,06/02/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Outros,NaN,NaN,Via Pública,Via Pública,S.PAULO,LIBERDADE,1506000.0,1,RUA GALVÃO BUENO,10.0,-23.559632,-46.634949,1005654735,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,LG,NaN,NaN,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
43,10101,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,2024,AB5526,2,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,02/01/2024,15:30:00,Pela Parte Interessada,02/01/2024,02/01/2024,06/02/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Outros,NaN,NaN,Via Pública,Via Pública,S.PAULO,LIBERDADE,1506000.0,1,RUA GALVÃO BUENO,10.0,-23.559632,-46.634949,1005654724,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Samsung,NaN,NaN,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
58,20120,DECAP,DEL.SEC.4º NORTE,20º D.P. AGUA FRIA,S.PAULO,2024,AC5308,1,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,03/01/2024,11:25:22,Pela Parte Interessada,03/01/2024,03/01/2024,03/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Interior de Veículo,NaN,"§ 2ºA, I - Se a violência ou ameaça é exercida...",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,10250020.0,1,AVENIDA DO ESTADO,1500.0,-23.540649,-46.628435,1005662514,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Motorola,S,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
59,20120,DECAP,DEL.SEC.4º NORTE,20º D.P. AGUA FRIA,S.PAULO,2024,AC5308,1,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,03/01/2024,11:25:22,Pela Parte Interessada,03/01/2024,03/01/2024,03/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Interior de Veículo,NaN,"§ 2º, II - há concurso de duas ou mais pessoas",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,10250020.0,1,AVENIDA DO ESTADO,1500.0,-23.540649,-46.628435,1005662514,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Motorola,S,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
71,900021,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA 1,S.PAULO,2024,AD4664,2,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,04/01/2024,06:00:00,Pela Parte Interessada,04/01/2024,04/01/2024,04/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Transeunte,NaN,"§ 2º, VII - se a violência ou grave ameaça é e...",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1501020.0,2,VIADUTO DONA PAULINA,80.0,-23.551971,-46.636156,1005670967,Subtraído,Telecomunicação,Telefone Celular,NaN,1,Samsung,N,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
72,900021,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA 1,S.PAULO,2024,AD4664,2,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,04/01/2024,06:00:00,Pela Parte Interessada,04/01/2024,04/01/2024,04/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Transeunte,NaN,"§ 2º, II - há concurso de duas ou mais pessoas",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1501020.0,2,VIADUTO DONA PAULINA,80.0,-23.551971,-46.636156,1005670967,Subtraído,Telecomunicação,Telefone Celular,NaN,1,Samsung,N,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
73,900021,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA 1,S.PAULO,2024,AD4664,2,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,04/01/2024,06:00:00,Pela Parte Interessada,04/01/2024,04/01/2024,04/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Transeunte,NaN,"§ 2º, VII - se a violência ou grave ameaça é e...",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1501020.0,2,VIADUTO DONA PAULINA,80.0,-23.551971,-46.636156,1005669344,Subtraído,Telecomunicação,Telefone Celular,NaN,1,Samsung,N,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
74,900021,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA 1,S.PAULO,2024,AD4664,2,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,04/01/2024,06:00:00,Pela Parte Interessada,04/01/2024,04/01/2024,04/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Transeunte,NaN,"§ 2º, II - há concurso de duas ou mais pessoas",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1501020.0,2,VIADUTO DONA PAULINA,80.0,-23.551971,-46.636156,1005669344,Subtraído,Telecomunicação,Telefone Celular,NaN,1,Samsung,N,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
107,20120,DECAP,DEL.SEC.4º NORTE,20º D.P. AGUA FRIA,S.PAULO,2024,AF8753,1,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,03/01/2024,NaN,Pela Parte Interessada,05/01/2024,05/01/2024,05/01/2024,De madrugada,D,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Interior de Veículo,NaN,"§ 2º, II - há concurso de duas ou mais pessoas",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,10250020.0,1,AVENIDA DO ESTADO,1500.0,-23.540649,-46.628435,1005686075,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Samsung,N,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
108,20120,DECAP,DEL.SEC.4º NORTE,20º D.P. AGUA FRIA,S.PAULO,2024,AF8753,1,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,03/01/2024,NaN,Pela Parte Interessada,05/01/2024,05/01/2024,05/01/2024,De madrugada,D,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Interior de Veículo,NaN,"§ 2º, II - há concurso de duas ou mais pessoas",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,10250020.0,1,AVENIDA DO ESTADO,1500.0,-23.540649,-46.628435,1005686075,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Samsung,S,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
137,900021,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA 1,S.PAULO,2024,AG8979,1,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,06/01/2024,NaN,Pela Parte Interessada,07/01/2024,06/01/2024,07/01/2024,Pela manhã,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Interior de Veículo,I - com destruição ou rompimento de obstáculo ...,§ 4º - A pena é de reclusão de 2 (dois) a 8 (o...,Via Pública,Via Pública,S.PAULO,SÉ,1024000.0,1,RUA DA CANTAREIRA,306.0,-23.541819,-46.629386,1005692524,Subtraído,Telecomunicação,Telefone Celular,NaN,1,Samsung,N,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
138,900021,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA 1,S.PAULO,2024,AG8979,1,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,06/01/2024,NaN,Pela Parte Interessada,07/01/2024,06/01/2024,07/01/2024,Pela manhã,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Interior de Veículo,I - com destruição ou rompimento de obstáculo ...,§ 4º - A pena é de reclusão de 2 (dois) a 8 (o...,Via Pública,Via Pública,S.PAULO,SÉ,1024000.0,1,RUA DA CANTAREIRA,306.0,-23.541819,-46.629386,1005692524,Subtraído,Telecomunicação,Telefone Celular,NaN,1,Samsung,S,N,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
144,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AH0194,3,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,07/01/2024,NaN,Por Integrantes da Polícia Militar,07/01/2024,07/01/2024,16/01/2024,De madrugada,C,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Outros,NaN,"§ 2º, II - há concurso de duas ou mais pessoas",Via Pública,Via Pública,S.PAULO,BOM RETIRO,11070000.0,2,AVENIDA DO ESTADO,3550.0,-23.529750,-46.626670,1005774094,Subtraído,Telecomunicação,Telefone Celular,Unidade,2,Samsung,NaN,NaN,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
145,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AH0194,3,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,07/01/2024,NaN,Por Integrantes da Polícia Militar,07/01/2024,07/01/2024,16/01/2024,De madrugada,C,N,NaN,N,CONSUMADO,Não Criminal,N,Localização/Apreensão e Entrega de veículo,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,BOM RETIRO,11070000.0,2,AVENIDA DO ESTADO,3550.0,-23.529750,-46.626670,1005774098,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Xiaomi,NaN,NaN,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
146,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AH0194,3,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,07/01/2024,NaN,Por Integrantes da Polícia Militar,07/01/2024,07/01/2024,16/01/2024,De madrugada,C,N,NaN,N,CONSUMADO,Não Criminal,N,Localização/Apreensão e Entrega de veículo,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,BOM RETIRO,11070000.0,2,AVENIDA DO ESTADO,3550.0,-23.529750,-46.626670,1005774094,Subtraído,Telecomunicação,Telefone Celular,Unidade,2,Samsung,NaN,NaN,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
147,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AH0194,3,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,07/01/2024,NaN,Por Integrantes da Polícia Militar,07/01/2024,07/01/2024,16/01/2024,De madrugada,C,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Outros,NaN,"§ 2º, II - há concurso de duas ou mais pessoas",Via Pública,Via Pública,S.PAULO,BOM RETIRO,11070000.0,2,AVENIDA DO ESTADO,3550.0,-23.529750,-46.626670,1005774105,Subtraído,Telecomunicação,Telefone Celular,Unidade,2,Motorola,NaN,NaN,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308

In [46]:
df_sp_geo.to_csv(
    'cel_sp_2024_clean.csv', sep = ';',
    index=False
)