# Filtro das cidades, veículos

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv ('VeiculosSubtraidos_2024.csv', sep = ';')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df.head(3)

C:\Users\Amazonas\AppData\Local\Temp\ipykernel_12508\2881841473.py:1: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv ('VeiculosSubtraidos_2024.csv', sep = ';')

,ID_DELEGACIA,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,ANO_BO,NUM_BO,VERSAO,CIDADE,NOME_DEPARTAMENTO_CIRC,NOME_SECCIONAL_CIRC,NOME_DELEGACIA_CIRC,NOME_MUNICIPIO_CIRC,DATA_OCORRENCIA_BO,HORA_OCORRENCIA,DESCRICAO_APRESENTACAO,DATAHORA_REGISTRO_BO,DATA_COMUNICACAO_BO,DATAHORA_IMPRESSAO_BO,DESCR_PERIODO,AUTORIA_BO,FLAG_INTOLERANCIA,TIPO_INTOLERANCIA,FLAG_FLAGRANTE,FLAG_STATUS,DESC_LEI,FLAG_ATO_INFRACIONAL,RUBRICA,DESCR_CONDUTA,DESDOBRAMENTO,CIRCUNSTANCIA,DESCR_TIPOLOCAL,DESCR_SUBTIPOLOCAL,CIDADE.1,BAIRRO,CEP,DESC_NATUREZA_LOCAL,LOGRADOURO_VERSAO,LOGRADOURO,NUMERO_LOGRADOURO,LATITUDE,LONGITUDE,CONT_VEICULO,DESCR_OCORRENCIA_VEICULO,DESCR_TIPO_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO,PLACA_VEICULO,DESC_COR_VEICULO,MES,ANO,CMD,BTL,CIA,CD_IBGE
0,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AE7772,1,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,04/01/2024,16:30:00,Pela Parte Interessada,05/01/2024,05/01/2024,05/01/2024,NaN,D,X,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Outros,NaN,"§ 2ºA, I - Se a violência ou ameaça é exercida...",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1015030.0,Fato,1,RUA SÃO NICOLAU,30.0,"-23,5476361","-46,6314771",1001973849,Roubado,Automovel,I/BMW 320I GRAN TURISMO,2015.0,NaN,FLL3G91,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
1,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AE7772,1,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,04/01/2024,16:30:00,Pela Parte Interessada,05/01/2024,05/01/2024,05/01/2024,NaN,D,X,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Outros,NaN,"§ 2º, V - o agente mantém a vítima em seu pode...",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1015030.0,Fato,1,RUA SÃO NICOLAU,30.0,"-23,5476361","-46,6314771",1001973849,Roubado,Automovel,I/BMW 320I GRAN TURISMO,2015.0,NaN,FLL3G91,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
2,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AE7772,1,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,04/01/2024,16:30:00,Pela Parte Interessada,05/01/2024,05/01/2024,05/01/2024,NaN,D,X,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Outros,NaN,"§ 2º, II - há concurso de duas ou mais pessoas",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1015030.0,Fato,1,RUA SÃO NICOLAU,30.0,"-23,5476361","-46,6314771",1001973849,Roubado,Automovel,I/BMW 320I GRAN TURISMO,2015.0,NaN,FLL3G91,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308

In [5]:
print("Total:", len(df))
print("\nRUBRICA:")
print(df['RUBRICA'].value_counts())

Total: 274733

RUBRICA:
RUBRICA
Furto (art. 155)                                                                                                 103388
Roubo (art. 157)                                                                                                  64389
Localização/Apreensão e Entrega de veículo                                                                        58728
Entrega de veículo localizado/apreendido                                                                          11668
Localização/Apreensão de veículo                                                                                   7941
Receptação (art. 180)                                                                                              6841
Adulteração de sinal identificador de veículo automotor (art. 311)                                                 3390
Localização/Apreensão de objeto                                                                                    3342
Localização/Apreensão e Entrega de objeto                                                                          1650
Encontro de Pessoa                                                                                                  879
Extorsão (art. 158)                                                                                                 868
Estelionato (art. 171)                                                                                              828
Outros não criminal                                                                                                 721
Caput Corromper ou facilitar a corrupção de menor de 18 anos (244B)                                                 628
Apropriação indébita (art. 168)                                                                                     621
Captura de procurado                                                                                                593
Associação Criminosa (art. 288)                                                                                     542
Dirigir sem Permissão ou Habilitação (Art. 309)                                                                     505
Desobediência (art. 330)                                                                                            484
Lesão corporal (art. 129)                                                                                           417
Lesão corporal culposa na direção de veículo automotor (Art. 303)                                                   401
Colisão                                                                                                             328
Resistência (art. 329)                                                                                              323
Desaparecimento de pessoa                                                                                           320
Entrega de objeto localizado/apreendido                                                                             282
Posse ou porte ilegal de arma de fogo de uso restrito (Art. 16)                                                     268
Embriaguez ao volante (Art. 306)                                                                                    261
Homicídio (art. 121)                                                                                                250
Comunicação falsa de crime ou contravenção (art. 340)                                                               237
Cumprimento de mandado de busca e apreensão                                                                         224
tráfico drogas (Art.33, caput)                                                                                      221
Ameaça (art. 147)                                                                                                   216
Dano (art. 163)                                                                                                     189
Extorsão mediante seqüestro (art. 159)                                                                              161
Violência Doméstica                                                                                                 140
Drogas para consumo pessoal sem autorização ou em desacordo (Art.28,caput)                                          123
Fuga de local de acidente (Art. 305)                                                                                116
Porte ilegal de arma de fogo de uso permitido (Art. 14)                                                             113
Drogas sem autorização ou em desacordo (Art.33, caput)                                                              113
Disparo de arma de fogo (Art. 15)                                                                                   110
Crime contra a ordem tributária (Art. 1º)                                                                            95
Choque                                                                                                               81
Homicídio culposo na direção de veículo automotor (Art. 302)                                                         71
Seqüestro e cárcere privado (art. 148)                                                                               70
Permitir direção de veículo automotor a pessoa não habilitada (Art. 310)                                             66
Posse irregular de arma de fogo de uso permitido (Art.12)                                                            64
Morte suspeita                                                                                                       63
Falsa identidade (art. 307)                                                                                          59
Uso de documento falso (art. 304)                                                                                    57
Apreensão de Adolescente                                                                                             51
Trafegar em velocidade incompatível (Art. 311)                                                                       51
Perda/Extravio                                                                                                       51
Exercício arbitrário das próprias razões (art. 345)                                                                  48
Cumprimento de mandado de prisão temporária                                                                          47
Incêndio (art. 250, caput)                                                                                           46
Corrupção ativa (art. 333)                                                                                           45
Desacato (art. 331)                                                                                                  44
Art 2º - Promover, constituir, financiar ou integrar organização criminosa                                           43
Injúria (art. 140)                                                                                                   42
ilícito extrapenal (tema 506 STF)                                                                                    41
Atropelamento                                                                                                        37
Furto de coisa comum (art. 156)                                                                                      37
Causar poluição de qualquer natureza (Art. 54)                                                                       35
Comunicação de óbito                                                                                                 33
Disparo de arma de fogo (art. 28)                                                                                    32
Associarem-se duas ou mais pessoas - arts. 33, caput e § 1o, e 34 (Art.35,caput)                                     27
Associação para o tráfico (Art.35,caput)                                                                             25
Favorecimento real (art. 349)                                                                                        24
Descumprimento de medida protetiva de urgência (art. 24-A)                                                           24
Tortura (Art. 1º)                                                                                                    23
Perturbação do trabalho ou do sossego alheios (art. 42)                                                              23
Jogo de azar (art. 50)                                                                                               21
Falsificação de documento público (art. 297)                                                                         20
Falsificação, corrupção, adulteração ou alteração de produto destinado a fins terapêuticos ou medicinais             17
Auto lesão                                                                                                           17
Direção perigosa de veículo na via pública (art. 34)                                                                 17
Queda acidental                                                                                                      16
Favorecimento pessoal (art. 348)                                                                                     16
Falsidade ideológica (art. 299)                                                                                      15
Produzir substância tóxica (Art. 56)                                                                                 14
Omissão de socorro (Art. 304)                                                                                        13
Abalroamento                                                                                                         11
Violação de domicílio (art. 150)                                                                                     11
Art. 308-Participar, na direção de veículo automotor, em via pública, de corrida                                     10
Suicídio consumado                                                                                                   10
Vias de fato (art. 21)                                                                                               10
Capotamento                                                                                                          10
Constrangimento ilegal (art. 146)                                                                                     9
Falta de habilitação para dirigir veículo (art. 32)                                                                   8
Perseguir (art. 147-A)                                                                                                8
Denunciação caluniosa (art. 339)                                                                                      8
Crime contra a ordem econômica (Art. 1º)                                                                              7
Alteração de limites (art. 161)                                                                                       7
Coação no curso do processo (art. 344)                                                                                7
Descaminho (Art 334)                                                                                                  6
Estupro - Art. 213                                                                                                    6
Praticar ato de abuso a animais (Art. 32)                                                                             5
Qq. objeto destinado a fabr., prep., prod. ou transformação de drogas (Art.34)                                        5
Usura pecuniária ou real (Art. 4º)                                                                                    5
Art. 213 - Estupro                                                                                                    5
Perigo para a vida ou saúde de outrem (art. 132)                                                                      5
Fals/corr/adult/alt produtos terapêuticos/medicinais (art. 273)                                                       5
Invasão de dispositivo informático                                                                                    5
Receptação de animal                                                                                                  4
Lavagem de dinheiro (Art. 1º)                                                                                         4
Porte de arma (art. 19)                                                                                               4
Instrumento de emprego usual na prática de furto (art. 24)                                                            4
Fraude processual (art. 347)                                                                                          4
Abandono material (art. 244)                                                                                          4
Art. 215A - Importunação Sexual                                                                                       4
Morte natural                                                                                                         4
Fabricação de drogas (Art.34)                                                                                         4
Moeda falsa (art. 289)                                                                                                4
Instalação ou utilização de telecomunicações (Art. 70)                                                                4
Falsificação de selo ou sinal público (art. 296)                                                                      4
Peculato (art. 312)                                                                                                   4
Recusa dados sobre própria identidade/qualific. (art. 68)                                                             3
Estupro de vulneravel (art.217-A)                                                                                     3
Omissão de socorro (Art. 135)                                                                                         3
Destruição, subtração ou ocultação de cadáver (art. 211)                                                              3
Fuga tentada                                                                                                          3
Falsificação de documento particular ou falsificação de cartão                                                        3
Tombamento                                                                                                            3
Usurpação de função pública (art. 328)                                                                                3
Omissão cautela na guarda/condução animais (art. 31)                                                                  2
Matar espécimes da fauna silvestre (Art. 29)                                                                          2
Colaborar com grupo, organização ou associação (Art.37)                                                               2
Crime contra as relações de consumo (Art. 7º)                                                                         2
Arremesso ou colocação perigosa (art. 37)                                                                             2
Ato obsceno (art.233)                                                                                                 2
Subtração, ocultação ou inutilização de material de salvamento (art. 257)                                             2
Fuga consumada                                                                                                        2
Posse não justificada de instr. de empr. no furto (art. 25)                                                           2
Corrupção de menores (art.218)                                                                                        2
Calúnia (art. 138)                                                                                                    2
Fraude à execução (art. 179)                                                                                          2
Violência psicológica contra a mulher (Art. 147-B)                                                                    2
Injuriar alguém, ofendendo-lhe a dignidade ou o decoro, em razão de raça, cor, etnia ou procedência nacional.         2
Construir estabelecimentos potencialmente poluidores (Art. 60)                                                        1
Difamação (art. 139)                                                                                                  1
Extrair pedra, areia, cal ou qualquer espécie de minerais (Art. 44)                                                   1
Divulgação de cena de estupro e imagens de nudez, sexo ou pornografia(Art.218-C)                                      1
Excesso na cobrança de dívidas (Art. 71)                                                                              1
Crime contra patente de invenção ou modelo de utilidade (Art. 184)                                                    1
Fabricar, vender, transportar ou soltar balões (Art. 42)                                                              1
Fuga de pessoa presa ou submetida a medida de segurança (art. 351)                                                    1
Violência arbitrária (art. 322)                                                                                       1
Falsa identidade, usar, como próprio, documento de identidade alheia (art. 308)                                       1
Exercício ilegal de profissão ou atividade (art. 47)                                                                  1
Abandono de incapaz (art. 133)                                                                                        1
Violação de suspensão/proibição (Art. 307)                                                                            1
Evasão mediante violência contra a pessoa (art. 352)                                                                  1
Crime contra registro de marca (Art. 190)                                                                             1
Outras fraudes (art. 176)                                                                                             1
Tirar, suprimir, destruir ou danificar coisa própria (art. 346)                                                       1
Destruir ou danificar vegetação primária ou secundária(Art.38-A)                                                      1
Destruir ou danificar floresta (Art. 38, caput)                                                                       1
Apropriar-se de bens do idoso (Art. 102)                                                                              1
Uso de documento falso (Art. 353)                                                                                     1
Subtração de incapazes (art. 249)                                                                                     1
Supressão de documento (art. 305)                                                                                     1
Desobediência à decisão judicial sobre perda ou suspensão de direito (art. 359)                                       1
Marketing de Emboscada por Intrusão                                                                                   1
Apropriação de coisa havida por erro, caso fortuito, força da natureza (art 169)                                      1
Name: count, dtype: int64

In [25]:
df['NOME_MUNICIPIO'].value_counts().head(20)

NOME_MUNICIPIO
S.PAULO                 111540
GUARULHOS                10592
S.ANDRE                   9848
CAMPINAS                  8358
OSASCO                    8211
S.BERNARDO DO CAMPO       7379
ITAQUAQUECETUBA           4459
MAUA                      4241
SOROCABA                  4168
CARAPICUIBA               3950
DIADEMA                   3437
SUZANO                    3150
RIBEIRAO PRETO            2896
PRAIA GRANDE              2852
SANTOS                    2517
TABOAO DA SERRA           2423
S.JOSE DO RIO PRETO       2263
S.VICENTE                 2257
COTIA                     2210
ITAPECERICA DA SERRA      2113
Name: count, dtype: int64

In [26]:
df['CIDADE'].value_counts().head(20)

CIDADE
S.PAULO                 111540
GUARULHOS                10592
S.ANDRE                   9848
CAMPINAS                  8358
OSASCO                    8211
S.BERNARDO DO CAMPO       7379
ITAQUAQUECETUBA           4459
MAUA                      4241
SOROCABA                  4168
CARAPICUIBA               3950
DIADEMA                   3437
SUZANO                    3150
RIBEIRAO PRETO            2896
PRAIA GRANDE              2852
SANTOS                    2517
TABOAO DA SERRA           2423
S.JOSE DO RIO PRETO       2263
S.VICENTE                 2257
COTIA                     2210
ITAPECERICA DA SERRA      2113
Name: count, dtype: int64

In [27]:
df.loc[
    df['NOME_MUNICIPIO'] != df['CIDADE'],
    ['NOME_MUNICIPIO', 'CIDADE']
].value_counts()

Series([], Name: count, dtype: int64)

In [28]:
filtro_sp = df['NOME_MUNICIPIO'].eq('S.PAULO')

df_sp = df.loc[filtro_sp].copy()

In [29]:
df_sp.shape

(111540, 56)

In [30]:
df_sp[['LATITUDE', 'LONGITUDE']].isna().sum()

LATITUDE     3663
LONGITUDE    3663
dtype: int64

In [31]:
df_sp_geo = df_sp.loc[
    df_sp['LATITUDE'].notna() &
    df_sp['LONGITUDE'].notna()
].copy()

df_sp_geo.shape

(107877, 56)

In [32]:
(df_sp_geo['LATITUDE'] == 0).sum()

(df_sp_geo['LONGITUDE'] == 0).sum()

0

In [33]:
df_sp['LATITUDE'] = pd.to_numeric(
    df_sp['LATITUDE'].astype(str).str.replace(',', '.', regex=False),
    errors='coerce'
)

df_sp['LONGITUDE'] = pd.to_numeric(
    df_sp['LONGITUDE'].astype(str).str.replace(',', '.', regex=False),
    errors='coerce'
)

In [34]:
df_sp[['LATITUDE', 'LONGITUDE']].dtypes

LATITUDE     float64
LONGITUDE    float64
dtype: object

In [35]:
df_sp_geo = df_sp.loc[
    df_sp['LATITUDE'].between(-24, -23) &
    df_sp['LONGITUDE'].between(-47, -46)
].copy()

df_sp_geo.shape

(100306, 56)

In [36]:
df_sp_geo.duplicated(
    subset=['NOME_DELEGACIA', 'ANO_BO', 'NUM_BO']
).sum()

44750

In [37]:
df_sp_geo[
    df_sp_geo.duplicated(
        subset=['NOME_DELEGACIA', 'ANO_BO', 'NUM_BO'],
        keep=False
    )
].head(20)

,ID_DELEGACIA,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,ANO_BO,NUM_BO,VERSAO,CIDADE,NOME_DEPARTAMENTO_CIRC,NOME_SECCIONAL_CIRC,NOME_DELEGACIA_CIRC,NOME_MUNICIPIO_CIRC,DATA_OCORRENCIA_BO,HORA_OCORRENCIA,DESCRICAO_APRESENTACAO,DATAHORA_REGISTRO_BO,DATA_COMUNICACAO_BO,DATAHORA_IMPRESSAO_BO,DESCR_PERIODO,AUTORIA_BO,FLAG_INTOLERANCIA,TIPO_INTOLERANCIA,FLAG_FLAGRANTE,FLAG_STATUS,DESC_LEI,FLAG_ATO_INFRACIONAL,RUBRICA,DESCR_CONDUTA,DESDOBRAMENTO,CIRCUNSTANCIA,DESCR_TIPOLOCAL,DESCR_SUBTIPOLOCAL,CIDADE.1,BAIRRO,CEP,DESC_NATUREZA_LOCAL,LOGRADOURO_VERSAO,LOGRADOURO,NUMERO_LOGRADOURO,LATITUDE,LONGITUDE,CONT_VEICULO,DESCR_OCORRENCIA_VEICULO,DESCR_TIPO_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO,PLACA_VEICULO,DESC_COR_VEICULO,MES,ANO,CMD,BTL,CIA,CD_IBGE
0,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AE7772,1,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,04/01/2024,16:30:00,Pela Parte Interessada,05/01/2024,05/01/2024,05/01/2024,NaN,D,X,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Outros,NaN,"§ 2ºA, I - Se a violência ou ameaça é exercida...",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1015030.0,Fato,1,RUA SÃO NICOLAU,30.0,-23.547636,-46.631477,1001973849,Roubado,Automovel,I/BMW 320I GRAN TURISMO,2015.0,NaN,FLL3G91,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
1,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AE7772,1,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,04/01/2024,16:30:00,Pela Parte Interessada,05/01/2024,05/01/2024,05/01/2024,NaN,D,X,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Outros,NaN,"§ 2º, V - o agente mantém a vítima em seu pode...",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1015030.0,Fato,1,RUA SÃO NICOLAU,30.0,-23.547636,-46.631477,1001973849,Roubado,Automovel,I/BMW 320I GRAN TURISMO,2015.0,NaN,FLL3G91,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
2,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AE7772,1,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,04/01/2024,16:30:00,Pela Parte Interessada,05/01/2024,05/01/2024,05/01/2024,NaN,D,X,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Outros,NaN,"§ 2º, II - há concurso de duas ou mais pessoas",Via Pública,Via Pública,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1015030.0,Fato,1,RUA SÃO NICOLAU,30.0,-23.547636,-46.631477,1001973849,Roubado,Automovel,I/BMW 320I GRAN TURISMO,2015.0,NaN,FLL3G91,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
4,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AH0194,3,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,07/01/2024,NaN,Por Integrantes da Polícia Militar,07/01/2024,07/01/2024,16/01/2024,De madrugada,C,N,NaN,N,CONSUMADO,Código Penal,N,Roubo (art. 157),Outros,NaN,"§ 2º, II - há concurso de duas ou mais pessoas",Via Pública,Via Pública,S.PAULO,BOM RETIRO,11070000.0,Fato,2,AVENIDA DO ESTADO,3550.0,-23.529750,-46.626670,1002006923,Localizado / Entregue,Camioneta,I/HONDA CR-V LX,2011.0,2011.0,EUS9727,Cinza,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
5,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AH0194,3,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,07/01/2024,NaN,Por Integrantes da Polícia Militar,07/01/2024,07/01/2024,16/01/2024,De madrugada,C,N,NaN,N,CONSUMADO,Não Criminal,N,Localização/Apreensão e Entrega de veículo,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,BOM RETIRO,11070000.0,Fato,2,AVENIDA DO ESTADO,3550.0,-23.529750,-46.626670,1002006923,Localizado / Entregue,Camioneta,I/HONDA CR-V LX,2011.0,2011.0,EUS9727,Cinza,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
6,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AH4095,1,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,07/01/2024,20:30:00,Por Integrantes da Polícia Militar,08/01/2024,07/01/2024,08/01/2024,NaN,C,X,NaN,S,CONSUMADO,Código Penal,N,Adulteração de sinal identificador de veículo ...,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,LIBERDADE,8230090.0,Fato,1,RUA GLICÉRIO,629.0,-23.556421,-46.629391,1001978712,Localizado / Entregue,Automovel,HONDA/FIT LXL,2003.0,2004.0,DHU8037,Dourada,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
7,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AH4095,1,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,07/01/2024,20:30:00,Por Integrantes da Polícia Militar,08/01/2024,07/01/2024,08/01/2024,NaN,C,X,NaN,S,CONSUMADO,Código Penal,N,Receptação (art. 180),Veículo,NaN,NaN,Via Pública,Via Pública,S.PAULO,LIBERDADE,8230090.0,Fato,1,RUA GLICÉRIO,629.0,-23.556421,-46.629391,1001978712,Localizado / Entregue,Automovel,HONDA/FIT LXL,2003.0,2004.0,DHU8037,Dourada,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
8,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AH4095,1,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,07/01/2024,20:30:00,Por Integrantes da Polícia Militar,08/01/2024,07/01/2024,08/01/2024,NaN,C,X,NaN,S,CONSUMADO,Não Criminal,N,Localização/Apreensão e Entrega de veículo,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,LIBERDADE,8230090.0,Fato,1,RUA GLICÉRIO,629.0,-23.556421,-46.629391,1001978712,Localizado / Entregue,Automovel,HONDA/FIT LXL,2003.0,2004.0,DHU8037,Dourada,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
13,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AN5709,2,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,11/01/2024,18:30:00,Pela Parte Interessada,11/01/2024,11/01/2024,17/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Veículo,NaN,NaN,Via Pública,Via Pública,S.PAULO,REPUBLICA,1314000.0,Fato,1,RUA SANTO ANTONIO,234.0,-23.550424,-46.641772,1001994166,Localizado / Entregue,Automovel,I/FORD RANGER XLT 13P,2010.0,NaN,MXE4B49,Prata,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
14,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AN5709,2,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,11/01/2024,18:30:00,Pela Parte Interessada,11/01/2024,11/01/2024,17/01/2024,NaN,D,N,NaN,N,CONSUMADO,Não Criminal,N,Localização/Apreensão e Entrega de veículo,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,REPUBLICA,1314000.0,Fato,1,RUA SANTO ANTONIO,234.0,-23.550424,-46.641772,1001994166,Localizado / Entregue,Automovel,I/FORD RANGER XLT 13P,2010.0,NaN,MXE4B49,Prata,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
16,10341,DECAP,DEL.SEC.1º CENTRO,77º D.P. SANTA CECILIA,S.PAULO,2024,AP4467,2,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,13/01/2024,14:14:00,Pela Parte Interessada,13/01/2024,13/01/2024,14/01/2024,NaN,D,N,NaN,N,CONSUMADO,Código Penal,N,Furto (art. 155),Veículo,NaN,NaN,Via Pública,Via Pública,S.PAULO,LIBERDADE,1502001.0,Fato,2,AVENIDA DA LIBERDADE,118.0,-23.559620,-46.637802,1001998500,Localizado / Entregue,Motociclo,HONDA/CG 160 FAN,2023.0,2023.0,SAX2G79,Prata,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
17,10341,DECAP,DEL.SEC.1º CENTRO,77º D.P. SANTA CECILIA,S.PAULO,2024,AP4467,2,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,13/01/2024,14:14:00,Pela Parte Interessada,13/01/2024,13/01/2024,14/01/2024,NaN,D,N,NaN,N,CONSUMADO,Não Criminal,N,Localização/Apreensão e Entrega de veículo,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,LIBERDADE,1502001.0,Fato,2,AVENIDA DA LIBERDADE,118.0,-23.559620,-46.637802,1001998500,Localizado / Entregue,Motociclo,HONDA/CG 160 FAN,2023.0,2023.0,SAX2G79,Prata,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
18,10341,DECAP,DEL.SEC.1º CENTRO,77º D.P. SANTA CECILIA,S.PAULO,2024,AP4467,2,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,13/01/2024,14:14:00,Pela Parte Interessada,13/01/2024,13/01/2024,14/01/2024,NaN,D,N,NaN,N,CONSUMADO,Não Criminal,N,Entrega de veículo localizado/apreendido,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,LIBERDADE,1502001.0,Fato,2,AVENIDA DA LIBERDADE,118.0,-23.559620,-46.637802,1001998500,Localizado / Entregue,Motociclo,HONDA/CG 160 FAN,2023.0,2023.0,SAX2G79,Prata,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
19,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AP8217,2,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,14/01/2024,02:30:00,Por Integrantes da Polícia Militar,14/01/2024,14/01/2024,19/01/2024,NaN,S,X,NaN,N,CONSUMADO,Código Penal,N,Receptação (art. 180),Veículo,NaN,NaN,Via Pública,Praça,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1022040.0,Fato,1,PRAÇA RAGUEB CHOHFI,386.0,-23.545571,-46.632021,1001999003,Localizado / Entregue,Automovel,I/HYUNDAI I30 1.8,2013.0,2014.0,FDR6563,Preta,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
20,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2024,AP8217,2,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,14/01/2024,02:30:00,Por Integrantes da Polícia Militar,14/01/2024,14/01/2024,19/01/2024,NaN,S,X,NaN,N,CONSUMADO,Não Criminal,N,Localização/Apreensão e Entrega de veículo,NaN,NaN,NaN,Via Pública,Praça,S.PAULO,CENTRO HISTÓRICO DE SÃO PAULO,1022040.0,Fato,1,PRAÇA RAGUEB CHOHFI,386.0,-23.545571,-46.632021,1001999003,Localizado / Entregue,Automovel,I/HYUNDAI I30 1.8,2013.0,2014.0,FDR6563,Preta,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
24,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AT7106,3,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,19/01/2024,15:50:00,Por Integrantes da Polícia Militar,17/01/2024,19/01/2024,31/01/2024,NaN,C,N,NaN,S,CONSUMADO,Código Penal,N,Furto (art. 155),Veículo,NaN,NaN,Via Pública,Via Pública,S.PAULO,SE,1512060.0,Prisão,2,RUA CAROLINA AUGUSTA,33.0,-23.553432,-46.631025,1002008662,Localizado / Entregue,Automovel,RENAULT/LOGAN AUT 1016V,2008.0,NaN,ETS0045,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
25,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AT7106,3,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,19/01/2024,15:50:00,Por Integrantes da Polícia Militar,17/01/2024,19/01/2024,31/01/2024,NaN,C,N,NaN,S,CONSUMADO,Não Criminal,N,Entrega de veículo localizado/apreendido,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,SE,1512060.0,Desdobramento,2,RUA CAROLINA AUGUSTA,33.0,-23.553432,-46.631025,1002008662,Localizado / Entregue,Automovel,RENAULT/LOGAN AUT 1016V,2008.0,NaN,ETS0045,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
26,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AT7106,3,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,19/01/2024,15:50:00,Por Integrantes da Polícia Militar,17/01/2024,19/01/2024,31/01/2024,NaN,C,N,NaN,S,CONSUMADO,Código Penal,N,Receptação (art. 180),Veículo,NaN,NaN,Via Pública,Via Pública,S.PAULO,SE,1512060.0,Desdobramento,2,RUA CAROLINA AUGUSTA,33.0,-23.553432,-46.631025,1002008662,Localizado / Entregue,Automovel,RENAULT/LOGAN AUT 1016V,2008.0,NaN,ETS0045,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
27,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AT7106,3,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,19/01/2024,15:50:00,Por Integrantes da Polícia Militar,17/01/2024,19/01/2024,31/01/2024,NaN,C,N,NaN,S,CONSUMADO,Não Criminal,N,Localização/Apreensão de veículo,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,SE,1512060.0,Prisão,2,RUA CAROLINA AUGUSTA,33.0,-23.553432,-46.631025,1002008662,Localizado / Entregue,Automovel,RENAULT/LOGAN AUT 1016V,2008.0,NaN,ETS0045,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
28,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AT7106,3,S.PAULO,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,19/01/2024,15:50:00,Por Integrantes da Polícia Militar,17/01/2024,19/01/2024,31/01/2024,NaN,C,N,NaN,S,CONSUMADO,Não Criminal,N,Entrega de veículo localizado/apreendido,NaN,NaN,NaN,Via Pública,Via Pública,S.PAULO,SE,1512060.0,Prisão,2,RUA CAROLINA AUGUSTA,33.0,-23.553432,-46.631025,1002008662,Localizado / Entregue,Automovel,RENAULT/LOGAN AUT 1016V,2008.0,NaN,ETS0045,Branco,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308

In [38]:
df_sp_geo.to_csv(
    'vei_sp_2024_clean.csv', sep = ';',
    index=False
)